/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ztx8iXVYBZB
 */
import { Avatar } from "@/components/ui/avatar"
import Image from "next/image"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

interface DashLayoutProps {
  userData: {
    family_name: string | null | undefined
    given_name: string | null | undefined
    picture: string | null | undefined
    email: string | null | undefined}
}

export function DashLayout({ userData }: DashLayoutProps) {
  return (
    <div className="w-full max-w-4xl px-4 py-6 space-y-6">
      <div className="flex items-center space-x-4">
        <Avatar className="w-12 h-12">
          <Image
            alt="use profile photo"
            className="rounded-full object-cover"
            height="48"
            src={userData.picture || "/placeholder-square.svg"}
            style={{
              aspectRatio: "48/48",
              objectFit: "cover",
            }}
            width="48"
          />
        </Avatar>
        <div className="space-y-1.5">
          <h1 className="text-3xl font-bold">Hi, {userData.given_name}</h1>
          <p className="text-gray-500 dark:text-gray-400">{userData.email}</p>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <h3 className="text-lg font-medium">My Grades</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">View your current grades</p>
          </CardHeader>
          <CardContent className="grid items-center p-6">
            <BookOpenIcon className="w-12 h-12" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <h3 className="text-lg font-medium">Course Schedule</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">View your upcoming classes</p>
          </CardHeader>
          <CardContent className="grid items-center p-6">
            <CalendarCheckIcon className="w-12 h-12" />
          </CardContent>
        </Card>
      </div>
    </div>
  )
}


function BookOpenIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  )
}


function CalendarCheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="m9 16 2 2 4-4" />
    </svg>
  )
}
