/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/giBH2HAlER0
 */
import { Skeleton } from "@/components/ui/skeleton"

export function DashLoader() {
  return (
    <div className="flex items-center justify-center">
      <div className="grid gap-4">
        <div className="flex items-center space-x-4">
          <Skeleton className="h-12 w-12 rounded-full" />
          <div className="space-y-2">
            <Skeleton className="h-4 w-[250px]" />
            <Skeleton className="h-4 w-[200px]" />
          </div>
        </div>
        <div className="grid items-center grid-cols-2">
          <div className="space-y-2">
            <Skeleton className="h-4 w-[200px]" />
            <Skeleton className="h-4 w-[100px]" />
          </div>
        </div>
        <div className="grid md:grid-cols-2 gap-4">
          <div className="grid grid-cols-2 gap-4">
            <Skeleton className="h-[180px]" />
            <Skeleton className="h-[180px]" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Skeleton className="h-[180px]" />
            <Skeleton className="h-[180px]" />
          </div>
        </div>
      </div>
    </div>
  )
}
