/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AF9Uck9q96I
 */
"use client";
import React, { useState } from "react";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function InterestsCard({ children }: { children: React.ReactNode; }) {
  const [inputInterests, setInputInterests] = useState<string[]>([]);
  const [selectedInterests, setSelectedInterests] = useState<string[]>([]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const interests = e.target.value.split(",");
    const sanitizedInterests: string[] = interests
      .map((interest) => interest.trim())
      .filter((interest) => interest !== "");
    setInputInterests(sanitizedInterests);
    console.log("input interests: ", sanitizedInterests);
  };

  const handleInterestSelect = (interest: string) => {
    const sanitizedInterest = interest.trim();
    if (sanitizedInterest !== "") {
      setSelectedInterests((prevInterests) => {
        const newInterests = [...prevInterests, sanitizedInterest];
        console.log("selected interests: ", newInterests);
        return newInterests;
      });
    }
  };

  return (
    <Card className="w-full max-w-md mx-auto">
      <div className="flex flex-col h-full">
        <CardHeader className="flex-shrink-0">
          <CardTitle className="text-xl">Your Interests</CardTitle>
          <CardDescription>
            what are you interested in?
          </CardDescription>
        </CardHeader>
        {children}
      </div>
    </Card>
  );
}
