/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AF9Uck9q96I
 */

import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";

export function InterestsCard({ children }: { children: React.ReactNode; }) {

  return (
    <Card className="w-full max-w-md mx-auto">
      <div className="flex flex-col h-full">
        <CardHeader className="flex-shrink-0">
          <CardTitle className="text-xl">Your Interests</CardTitle>
          <CardDescription>
            what are you interested in?
          </CardDescription>
        </CardHeader>
        {children}
      </div>
    </Card>
  );
}
