/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lxoQVts8vhT
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export default function OnboardingComponent() {
  return (
    <Card className="w-full max-w-lg">
      <div className="flex flex-col h-full">
        <CardHeader className="flex-shrink-0">
          <CardTitle className="text-xl">Step 1: Course Information</CardTitle>
          <CardDescription>Enter your course major to get started</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col justify-center space-y-4">
          <Input placeholder="Course Major" />
        </CardContent>
        <CardFooter className="mt-auto flex gap-4">
          <Button size="sm" variant="outline">
            Previous
          </Button>
          <Button size="sm">Next</Button>
        </CardFooter>
      </div>
    </Card>
  )
}
