/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lxoQVts8vhT
 */
// import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
// import { Input } from "@/components/ui/input"
// import { Button } from "@/components/ui/button"

// export default function OnboardingComponent() {
//   return (
//     <Card className="w-full max-w-lg">
//       <div className="flex flex-col h-full">
//         <CardHeader className="flex-shrink-0">
//           <CardTitle className="text-xl">Step 1: Course Information</CardTitle>
//           <CardDescription>Enter your course major to get started</CardDescription>
//         </CardHeader>
//         <CardContent className="flex flex-col justify-center space-y-4">
//           <Input placeholder="Course Major" />
//         </CardContent>
//         <CardFooter className="mt-auto flex gap-4">
//           <Button size="sm" variant="outline">
//             Previous
//           </Button>
//           <Button size="sm">Next</Button>
//         </CardFooter>
//       </div>
//     </Card>
//   )
// }


import React, { useState } from 'react';
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export default function OnboardingComponent() {
  const [currentCard, setCurrentCard] = useState(1);

  const nextCard = () => {
    setCurrentCard(prevCard => prevCard + 1);
  }

  const prevCard = () => {
    setCurrentCard(prevCard => prevCard - 1);
  }

  return (
    <div>
      {currentCard === 1 && (
        <Card className="w-full max-w-lg">
          <div className="flex flex-col h-full">
            <CardHeader className="flex-shrink-0">
              <CardTitle className="text-xl">Card 1</CardTitle>
              <CardDescription>Description for Card 1</CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col justify-center space-y-4">
              <Input placeholder="Course Major" />
            </CardContent>
            <CardFooter className="mt-auto flex gap-4">
              <Button size="sm" onClick={nextCard}>
                Next Card
              </Button>
            </CardFooter>
          </div>
        </Card>
      )}

      {currentCard === 2 && (
        <Card className="w-full max-w-lg">
          <div className="flex flex-col h-full">
            <CardHeader className="flex-shrink-0">
              <CardTitle className="text-xl">Card 2</CardTitle>
              <CardDescription>Description for Card 2</CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col justify-center space-y-4">
            <Input placeholder="Institution" />
            </CardContent>
            <CardFooter className="mt-auto flex gap-4">
              <Button size="sm" variant="outline" onClick={prevCard}>
                Previous Card
              </Button>
              <Button size="sm" onClick={nextCard}>
                Next Card
              </Button>
            </CardFooter>
          </div>
        </Card>
      )}

      {/* Add more cards as needed */}
    </div>
  )
}
