/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Zw6L8zkFSLb
 */
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function SearchPageLayout() {
  return (
    <div className="dark:bg-gray-950 py-12 md:py-16">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center gap-4 md:gap-8">
          <div className="text-center">
            <h1 className="text-3xl font-bold tracking-tight">Search Notes</h1>
            <p className="text-gray-500 dark:text-gray-400">Enter keywords or select a category to filter results</p>
          </div>
          <div className="w-full max-w-[500px]">
            <form className="flex flex-col gap-2">
              <Input className="w-full max-w-[500px]" placeholder="Search by keyword" type="search" />
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select a category" />
                </SelectTrigger>
                <SelectContent className="w-full">
                  <SelectItem value="all">All Categories</SelectItem>
                  <SelectItem value="science">Science</SelectItem>
                  <SelectItem value="history">History</SelectItem>
                  <SelectItem value="math">Math</SelectItem>
                  <SelectItem value="literature">Literature</SelectItem>
                </SelectContent>
              </Select>
              <Button type="submit">Search</Button>
            </form>
          </div>
          <div className="grid gap-4 w-full max-w-md">
            <div className="border p-4 rounded-lg flex items-center justify-between">
              <div className="flex items-center gap-4">
                <BookmarkIcon className="w-6 h-6 fill-gray-900 dark:fill-gray-50" />
                <div>
                  <h3 className="font-semibold">The Water Cycle</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Science · 5 mins ago</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <ThumbsUpIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <span>10</span>
                <EyeIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <span>25</span>
              </div>
              <Button size="sm" variant="outline">
                View Note
              </Button>
            </div>
            <div className="border p-4 rounded-lg flex items-center justify-between">
              <div className="flex items-center gap-4">
                <BookmarkIcon className="w-6 h-6 fill-gray-900 dark:fill-gray-50" />
                <div>
                  <h3 className="font-semibold">World War II Timeline</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">History · 2 days ago</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <ThumbsUpIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <span>8</span>
                <EyeIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <span>20</span>
              </div>
              <Button size="sm" variant="outline">
                View Note
              </Button>
            </div>
            <div className="border p-4 rounded-lg flex items-center justify-between">
              <div className="flex items-center gap-4">
                <BookmarkIcon className="w-6 h-6 fill-gray-900 dark:fill-gray-50" />
                <div>
                  <h3 className="font-semibold">Algebra Formulas</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Math · 1 hour ago</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <ThumbsUpIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <span>12</span>
                <EyeIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                <span>30</span>
              </div>
              <Button size="sm" variant="outline">
                View Note
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function BookmarkIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function ThumbsUpIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}


function EyeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
