/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IOmtsBvNJPu
 */
import { Avatar } from "@/components/ui/avatar"
import Image from "next/image"
import { CardContent, Card } from "@/components/ui/card"
import React from "react";

interface UserData {
  family_name: string | null;
  given_name: string | null;
  picture: string | null;
  email: string | null;
  id: string | null;
}

interface WelcomeOnboardProps {
  userData?: UserData;
  children?: React.ReactNode
}


export function WelcomeOnboard({ userData, children }: WelcomeOnboardProps) {
  let pfpSrc = "";
  if (userData?.picture) {
    pfpSrc = userData.picture
  } else {
    pfpSrc = "/placeholder-user.jpg"

  }
  return (
    <Card className={`w-full max-w-lg min-w-md mx-auto`}>
      <CardContent className="p-6">
        <div className="flex items-center space-x-4">
          <Avatar>
            <Image
              alt="Avatar"
              height="40"
              src={pfpSrc}
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width="40"
            />
          </Avatar>
          <div className="grid gap-1.5">
            <h1 className="text-lg font-bold tracking-tighter">Hi, {userData?.given_name?.toLocaleLowerCase()}</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">{userData?.email}</p>
          </div>
        </div>
      </CardContent>
      {/* create a div ans style it using tailwind to make a gray divider between the content before and after the div. */}
      <div className="h-px bg-gray-200 dark:bg-gray-800 w-9/12 mx-auto" />
      <CardContent className="p-6">
        <div className="space-y-4">
          <h2 className="text-lg font-bold">Welcome to Jadi, {userData?.given_name?.toLocaleLowerCase()}</h2>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            We&apos;re excited to have you on board. If you have any questions, feel free to reach out to our support team.
          </p>
        </div>
      </CardContent>
      <CardContent className="p-6">
        { children }
      </CardContent>
    </Card>
  )
}
