/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PBcruX1S0Ie
 */

import { LoginLink, RegisterLink } from "@kinde-oss/kinde-auth-nextjs/components"
import { Button } from "@/components/ui/button";
import styles from "./styles.module.css"
import Link from "next/link";

export function ErrorPageProtectedLayout() {
  return (
    <div className={`${styles.layout_wrapper} flex items-center justify-center w-full flex-col space-y-8`}>
      <div className="flex flex-col items-center justify-between space-y-2 text-center">
        <LockIcon className="h-16 w-16 direction-alternate ease-in animate-pulse duration-1000" />
        <div className={`${styles.text_content}`}>
          <h1 className="text-4xl font-bold mt-12 mb-5">Protected view</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-12">This page is protected. Please login to access this page.</p>
        </div>
      </div>
      
      <div>
        <LoginLink>
                  <Button
                    className={`${styles.auth_button}`}
                    variant="default"
                    size={"lg"}
                  >
                    Login
                    <svg
                      className={`${styles.btn_icon} ms-3`}
                      width="7"
                      height="12"
                      viewBox="0 0 7 12"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M6.82894 6.38589L0.996255 11.8402C0.942063 11.8908 0.877728 11.931 0.806924 11.9585C0.736119 11.9859 0.660231 12 0.583592 12C0.506954 12 0.431066 11.9859 0.360261 11.9585C0.289456 11.931 0.225122 11.8908 0.17093 11.8402C0.116738 11.7895 0.0737513 11.7293 0.0444231 11.6631C0.0150948 11.5969 0 11.5259 0 11.4543C0 11.3826 0.0150948 11.3116 0.0444231 11.2454C0.0737513 11.1792 0.116738 11.1191 0.17093 11.0684L5.59168 6L0.17093 0.93162C0.0614851 0.829275 -1.15319e-09 0.690467 0 0.54573C1.15319e-09 0.400994 0.0614851 0.262185 0.17093 0.159841C0.280375 0.0574964 0.428814 1.07837e-09 0.583592 0C0.738371 -1.07837e-09 0.88681 0.0574964 0.996255 0.159841L6.82894 5.61411C6.88317 5.66476 6.92619 5.72492 6.95554 5.79113C6.98489 5.85735 7 5.92832 7 6C7 6.07168 6.98489 6.14265 6.95554 6.20887C6.92619 6.27508 6.88317 6.33523 6.82894 6.38589Z"
                        fill="black"
                      />
                    </svg>
                  </Button>
        </LoginLink>
        <RegisterLink postLoginRedirectURL="/onboarding" className="ms-3">
                  <Button
                    className={`${styles.auth_button} bg-green-500 hover:bg-green-300`}
                    variant="default"
                    size={"lg"}
                  >
                    Create Account
                    <svg
                      className={`${styles.btn_icon} ms-3`}
                      width="7"
                      height="12"
                      viewBox="0 0 7 12"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M6.82894 6.38589L0.996255 11.8402C0.942063 11.8908 0.877728 11.931 0.806924 11.9585C0.736119 11.9859 0.660231 12 0.583592 12C0.506954 12 0.431066 11.9859 0.360261 11.9585C0.289456 11.931 0.225122 11.8908 0.17093 11.8402C0.116738 11.7895 0.0737513 11.7293 0.0444231 11.6631C0.0150948 11.5969 0 11.5259 0 11.4543C0 11.3826 0.0150948 11.3116 0.0444231 11.2454C0.0737513 11.1792 0.116738 11.1191 0.17093 11.0684L5.59168 6L0.17093 0.93162C0.0614851 0.829275 -1.15319e-09 0.690467 0 0.54573C1.15319e-09 0.400994 0.0614851 0.262185 0.17093 0.159841C0.280375 0.0574964 0.428814 1.07837e-09 0.583592 0C0.738371 -1.07837e-09 0.88681 0.0574964 0.996255 0.159841L6.82894 5.61411C6.88317 5.66476 6.92619 5.72492 6.95554 5.79113C6.98489 5.85735 7 5.92832 7 6C7 6.07168 6.98489 6.14265 6.95554 6.20887C6.92619 6.27508 6.88317 6.33523 6.82894 6.38589Z"
                        fill="black"
                      />
                    </svg>
                  </Button>
        </RegisterLink>
      </div>
      <Link href="/">
      <Button variant="link" size={"sm"}>
      <svg width="5" height="9" viewBox="0 0 5 9" className="me-3" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M0.122189 4.78942L4.28839 8.88012C4.3271 8.91813 4.37305 8.94827 4.42363 8.96884C4.4742 8.98941 4.52841 9 4.58315 9C4.63789 9 4.6921 8.98941 4.74267 8.96884C4.79325 8.94827 4.8392 8.91813 4.87791 8.88012C4.91662 8.84211 4.94732 8.79699 4.96827 8.74733C4.98922 8.69768 5 8.64445 5 8.5907C5 8.53695 4.98922 8.48373 4.96827 8.43407C4.94732 8.38441 4.91662 8.33929 4.87791 8.30128L1.00594 4.5L4.87791 0.698715C4.95608 0.621957 5 0.51785 5 0.409298C5 0.300745 4.95608 0.196639 4.87791 0.11988C4.79973 0.0431223 4.6937 8.08779e-10 4.58315 0C4.47259 -8.08779e-10 4.36656 0.0431223 4.28839 0.11988L0.122189 4.21058C0.0834528 4.24857 0.0527232 4.29369 0.031757 4.34335C0.0107909 4.39301 6.25167e-08 4.44624 6.25167e-08 4.5C6.25167e-08 4.55376 0.0107909 4.60699 0.031757 4.65665C0.0527232 4.70631 0.0834528 4.75143 0.122189 4.78942Z" fill="white"/>
      </svg>

      Back Home
      </Button>
      </Link>
    </div>
  )
}


function LockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="red"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}

